### ISSUE TITLE
Existing Velodyne simulator

### ISSUE THREAD

**Issue by kmhallen** [RyodoTanaka/velodyne_gazebo#1]
Have you tried the existing simulator?
http://wiki.ros.org/velodyne_simulator
https://bitbucket.org/DataspeedInc/velodyne_simulator

**Comment by RyodoTanaka** [comment]
@kmhallen 
Yes, I tried that simulator. And it works fine.
But I wanted to make more real one.
Following [the velodyne gazebo tutorial](http://gazebosim.org/tutorials?tut=guided_i1), it seems that we can create a rotating velodyne simulator from jade.
And I wanted to create that rotating simulator on indigo.
As a result, I achieve some functions, but not completely...
- I could make a function that is the same as [SetVelocity()](https://bitbucket.org/osrf/gazebo/src/8f65af9d519d70e03a8f7ea99f669d140001d7d3/gazebo/physics/Joint.hh?at=default&fileviewer=file-view-default) function.
- I could read the state of joints and links.

But, there is a problem...
- To make it real, we need to get the joint state in very high rate. But it is too fast that I couldn't Implement it.  
  The real velodyne sensor (HDL-32E) gets 700,000 [points/s]. That means, If we set the rotating rate to 10 [Hz], we need to get the range data every 0.16457142857 [deg]. That is too narrow, and the interrupt couldn't catch up that.

So now, I think we should use the simulator you mentioned.
I'd appreciate it If you know the solution and tell me.

Best regards, Thank you.

**Comment by kmhallen** [comment]
I don't see a good solution.

Gazebo is unable to keep up with the number of times your simulator wants to stop and take a measurement.

With mine, gazebo is unable to keep up with 10Hz using the VLP-16, and can't update the HDL-32E at all (unless the angular resolution is reduced).

**Comment by RyodoTanaka** [comment]
@kmhallen 
Thank you for telling.

I forgot to tell you that I have found one solution.
With following simulation time, we can get the angular resolution that we need.

``` xml
    <physics type='ode'>
      <max_step_size>0.00001000</max_step_size>
      <real_time_factor>1.000000</real_time_factor>
      <real_time_update_rate>100000.000000</real_time_update_rate>
    </physics>
```

Of course, the simulation will be slow.
Any way, we have no solution to get the angular resolution that we need with normal speed simulation...
